
CREATE TABLE PERSON (
    ID   INTEGER      AUTO_INCREMENT PRIMARY KEY,
    CPF  VARCHAR(11)  NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PERSON_PHONE (
    PERSON_ID INTEGER,
    PHONE     VARCHAR(20),

    PRIMARY KEY (PERSON_ID, PHONE),

    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM (
    ID           INTEGER      AUTO_INCREMENT PRIMARY KEY,
    CNPJ         VARCHAR(14)  NOT NULL UNIQUE,
    NAME         VARCHAR(100) NOT NULL,
    NUMBER       INTEGER      NOT NULL,
    CEP          VARCHAR(8)   NOT NULL,
    COMPLEMENT   VARCHAR(100) DEFAULT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL
);

CREATE TABLE EMPLOYEE (
    PERSON_ID      INTEGER,
    SALARY         DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    ROLE           VARCHAR(50)   NOT NULL,
    CONDOMINIUM_ID INTEGER       NOT NULL,
    WORKPLACE      VARCHAR(100)  DEFAULT NULL,
    START_TIME     TIME          NOT NULL,
    END_TIME       TIME          NOT NULL,

    PRIMARY KEY (PERSON_ID),

    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,

    FOREIGN KEY (CONDOMINIUM_ID) REFERENCES CONDOMINIUM(ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE RESIDENT (
    PERSON_ID        INTEGER,
    TYPE             VARCHAR(50) NOT NULL,
    PRIMARY_OCCUPANT BOOLEAN     NOT NULL DEFAULT FALSE,

    PRIMARY KEY (PERSON_ID),

    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DEPENDENT (
    PERSON_ID    INTEGER,
    NAME         VARCHAR(100),
    BIRTH_DATE   DATE        NOT NULL,
    RELATIONSHIP VARCHAR(50) NOT NULL,

    PRIMARY KEY (PERSON_ID, NAME, BIRTH_DATE),

    FOREIGN KEY (PERSON_ID) REFERENCES RESIDENT(PERSON_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE APARTMENT (
    NUMBER         INTEGER,
    CONDOMINIUM_ID INTEGER,
    FLOOR          INTEGER     DEFAULT NULL,
    STATUS         VARCHAR(30) NOT NULL,

    PRIMARY KEY (NUMBER, CONDOMINIUM_ID),

    FOREIGN KEY (CONDOMINIUM_ID) REFERENCES CONDOMINIUM(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM_FEE (
    ID              INTEGER       AUTO_INCREMENT PRIMARY KEY,
    REFERENCE_MONTH DATE          NOT NULL,
    DUE_DATE        DATE          NOT NULL,
    PAYMENT_DATE    DATE          DEFAULT NULL,
    AMOUNT          DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    LATE_FEE        DECIMAL(15,2) DEFAULT 0.00,
    STATUS          VARCHAR(20)   NOT NULL DEFAULT 'Pending'
);

CREATE TABLE OCCUPANCY (
    RESIDENT_ID        INTEGER,
    APT_NUMBER         INTEGER,
    APT_CONDOMINIUM_ID INTEGER,
    START_DATE         DATE NOT NULL,
    END_DATE           DATE DEFAULT NULL,

    PRIMARY KEY (RESIDENT_ID, APT_NUMBER, APT_CONDOMINIUM_ID),

    FOREIGN KEY (RESIDENT_ID) REFERENCES RESIDENT(PERSON_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,

    FOREIGN KEY (APT_NUMBER, APT_CONDOMINIUM_ID) REFERENCES APARTMENT(NUMBER, CONDOMINIUM_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CHARGES (
    RESIDENT_ID        INTEGER,
    APT_NUMBER         INTEGER,
    APT_CONDOMINIUM_ID INTEGER,
    CONDOMINIUM_FEE_ID INTEGER,

    PRIMARY KEY (RESIDENT_ID, APT_NUMBER, APT_CONDOMINIUM_ID, CONDOMINIUM_FEE_ID),

    FOREIGN KEY (RESIDENT_ID) REFERENCES RESIDENT(PERSON_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,

    FOREIGN KEY (APT_NUMBER, APT_CONDOMINIUM_ID) REFERENCES APARTMENT(NUMBER, CONDOMINIUM_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,

    FOREIGN KEY (CONDOMINIUM_FEE_ID) REFERENCES CONDOMINIUM_FEE(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);