CREATE DATABASE condominium_management_system;
USE condominium_management_system;
SHOW TABLES;

CREATE TABLE PERSON(
ID INTEGER PRIMARY KEY,
CPF VARCHAR(11) NOT NULL UNIQUE,
NAME VARCHAR(100) NOT NULL,
ROLE VARCHAR(50) DEFAULT NULL,
SALARY DECIMAL (15,2) DEFAULT 0.00,
TYPE VARCHAR(50) DEFAULT NULL,
PRIMARY_OCCUPANT BOOLEAN DEFAULT FALSE,
PERSON_TYPE VARCHAR(12) NOT NULL
);

CREATE TABLE PERSON_PHONE(
PERSON_ID INTEGER,
PHONE VARCHAR(20),

PRIMARY KEY (PERSON_ID, PHONE),
FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DEPENDENT(
PERSON_ID INTEGER,
NAME VARCHAR(100),
RELATIONSHIP VARCHAR(50) NOT NULL,

PRIMARY KEY (PERSON_ID, NAME),
FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM(
ID INTEGER PRIMARY KEY,
CNPJ VARCHAR(14) NOT NULL UNIQUE,
NAME VARCHAR(100) NOT NULL,
NUMBER INTEGER NOT NULL,
CEP VARCHAR(8) NOT NULL,
COMPLEMENT VARCHAR(100) DEFAULT NULL,
NEIGHBORHOOD VARCHAR(100),
START_TIME TIME NOT NULL,
END_TIME TIME NOT NULL,
WORKPLACE VARCHAR(100) DEFAULT NULL
);

CREATE TABLE APARTMENT(
NUMBER INTEGER,
CONDOMINIUM_ID INTEGER,
CONDO_FEE DECIMAL(15,2) DEFAULT 0.00 NOT NULL,

PRIMARY KEY (NUMBER, CONDOMINIUM_ID),
FOREIGN KEY(CONDOMINIUM_ID) REFERENCES CONDOMINIUM(ID)
);

CREATE TABLE LIVES_PERSON_CONDOMINIUM_APARTMENT(
FK_NUMBER INTEGER,
FK_PERSON_ID INTEGER,
FK_CONDOMINIUM_ID INTEGER,
AMOUNT DECIMAL(15,2) NOT NULL,
PAYMENT_STATUS VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
REFERENCE_DATE DATE NOT NULL,
PAYMENT_DATE DATE,
DUE_DATE DATE NOT NULL,
LATE_FEE DECIMAL(15,2),

FOREIGN KEY (FK_NUMBER, FK_CONDOMINIUM_ID) REFERENCES APARTMENT(NUMBER, CONDOMINIUM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (FK_PERSON_ID) REFERENCES PERSON(ID) ON DELETE CASCADE ON UPDATE CASCADE,

PRIMARY KEY (FK_NUMBER, FK_PERSON_ID, FK_CONDOMINIUM_ID)
);