
SELECT P.NAME, E.ROLE, E.SALARY, E.WORKPLACE --  List all employees with their role, salary and workplace
FROM PERSON P
JOIN EMPLOYEE E ON P.ID = E.PERSON_ID
ORDER BY E.SALARY DESC;

SELECT P.NAME, D.NAME AS DEPENDENT, D.RELATIONSHIP -- List all residents with their dependents
FROM PERSON P
JOIN RESIDENT R ON P.ID = R.PERSON_ID
LEFT JOIN DEPENDENT D ON R.PERSON_ID = D.PERSON_ID;

SELECT P.NAME, O.APT_NUMBER, C.NAME AS CONDOMINIUM -- List all residents with name, apartment number and condominium
FROM PERSON P
JOIN RESIDENT R ON P.ID = R.PERSON_ID
JOIN OCCUPANCY O ON R.PERSON_ID = O.RESIDENT_ID
JOIN CONDOMINIUM C ON C.ID = O.APT_CONDOMINIUM_ID
WHERE O.END_DATE IS NULL;

SELECT P.NAME, CF.AMOUNT, CF.DUE_DATE, CF.LATE_FEE -- List all overdue fee records with the responsible resident
FROM CHARGES CH
JOIN RESIDENT R ON CH.RESIDENT_ID = R.PERSON_ID
JOIN PERSON P ON R.PERSON_ID = P.ID
JOIN CONDOMINIUM_FEE CF ON CH.CONDOMINIUM_FEE_ID = CF.ID
WHERE CF.STATUS = 'Overdue';

SELECT C.NAME AS CONDOMINIUM, COUNT(DISTINCT O.RESIDENT_ID) AS TOTAL_RESIDENTS -- Count residents per condominium
FROM OCCUPANCY O
JOIN CONDOMINIUM C ON C.ID = O.APT_CONDOMINIUM_ID
WHERE O.END_DATE IS NULL
GROUP BY C.NAME
HAVING COUNT(DISTINCT O.RESIDENT_ID) >= 1;

SELECT P.NAME, COUNT(D.NAME) AS TOTAL_DEPENDENTS -- Count dependents per resident
FROM PERSON P JOIN RESIDENT R ON P.ID = R.PERSON_ID
LEFT JOIN DEPENDENT D ON R.PERSON_ID = D.PERSON_ID
GROUP BY P.NAME HAVING COUNT(D.NAME) >= 1;

SELECT DISTINCT P.NAME -- List residents with at least one overdue fee
FROM PERSON P
JOIN RESIDENT R ON P.ID = R.PERSON_ID
JOIN CHARGES CH ON R.PERSON_ID = CH.RESIDENT_ID
JOIN CONDOMINIUM_FEE CF ON CH.CONDOMINIUM_FEE_ID = CF.ID
WHERE CF.STATUS = 'Overdue';

SELECT NAME FROM CONDOMINIUM -- List condominiums that have at least one apartment registered
WHERE ID IN (SELECT CONDOMINIUM_ID FROM APARTMENT);

SELECT P.NAME, PP.PHONE -- List all phones registered in the system
FROM PERSON P
JOIN PERSON_PHONE PP ON P.ID = PP.PERSON_ID;

SELECT A.NUMBER, C.NAME AS CONDOMINIUM, A.FLOOR, A.STATUS -- List all apartments with their floor and status
FROM APARTMENT A
JOIN CONDOMINIUM C ON C.ID = A.CONDOMINIUM_ID;