SELECT NAME, ROLE, SALARY FROM PERSON
WHERE PERSON_TYPE = 'Employee';

SELECT P.NAME, D.NAME AS DEPENDENT FROM PERSON P
LEFT JOIN DEPENDENT D ON P.ID = D.PERSON_ID;

SELECT NAME, SALARY FROM PERSON WHERE PERSON_TYPE = 'Employee' 
ORDER BY SALARY DESC;

SELECT FK_PERSON_ID, AMOUNT, PAYMENT_STATUS,
FROM LIVES_PERSON_CONDOMINIUM_APARTMENT WHERE PAYMENT_STATUS = 'OVERDUE';

SELECT P.NAME, A.NUMBER, C.NAME AS CONDOMINIUM FROM PERSON P
JOIN LIVES_PERSON_CONDOMINIUM_APARTMENT L ON P.ID = L.FK_PERSON_ID
JOIN APARTMENT A ON A.NUMBER = L.FK_NUMBER AND A.CONDOMINIUM_ID = L.FK_CONDOMINIUM_ID
JOIN CONDOMINIUM C ON C.ID = A.CONDOMINIUM_ID;

SELECT FK_CONDOMINIUM_ID, COUNT(*) AS TOTAL_MORADORES FROM LIVES_PERSON_CONDOMINIUM_APARTMENT
GROUP BY FK_CONDOMINIUM_ID HAVING COUNT(*) >= 2;


SELECT PERSON_ID, COUNT(*) AS TOTAL_DEPENDENTES FROM DEPENDENT
GROUP BY PERSON_ID HAVING COUNT(*) >= 1;

SELECT NAME FROM PERSON WHERE ID IN ( SELECT FK_PERSON_ID
FROM LIVES_PERSON_CONDOMINIUM_APARTMENT WHERE PAYMENT_STATUS = 'OVERDUE'
);

SELECT NAME FROM CONDOMINIUM
WHERE ID IN ( SELECT CONDOMINIUM_ID FROM APARTMENT );

